/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {

    //PK is defaut sails id field
    attributes: {
        birdID: {
            model: "Bird",
            required: true
        },
        nestID: {
            model: "Nestsite",
            required: true
        },
        dateEntered: {
            type: "ref",
            columnType: "date",
            required: true
        },
        dateLeft: {
            type: "ref",
            columnType: "date"
        }
    }
};