/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {
    updatedAt: false,
    attributes: {
        //entryDate added by sails
        //primaryKey provided by sails ID

        birdID: {
            model: "Bird"
        },
        birdCondition: {
            type: "string",
            columnType: "varchar",
            maxLength: 200
        }
        
    }
};