/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {
    autoPK: false,
    autoCreatedAt: false,

    attributes: {
        birdID: {
            model: Bird,
            primaryKey: true
        },
        birdCondition: {
            type: "string",
            columnType: "varchar",
            maxLength: 200
        }
        //updatedAt added by sails
    }
};