/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {
    attributes: {
        updatedAt: false,
        createdBy: false,
        updatedBy: false,
        
        user: {
            model: "user",
            required: true
        },
        action: {
            type: "ref",
            columnType: "varchar",
            required: true
        },
        newData: {
            type: "ref",
            columnType: "text"
        },
        oldData: {
            type: "ref",
            columnType: "text"
        }
    }
};