/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {

    primaryKey: "feederID",

    attributes: {
        id: false,
        updatedAt: false,
        createdAt: false,
        feederID: {
            type: 'number',
            autoIncrement: true,
            required: true
        },
        createdBy: {
            model: "user"
        },
        feederDescription: {
            type: "string",
            columnType: "varchar",
            maxLength: 200
        }
    }
};