/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time) 
*/

module.exports = {
    attributes: {
        updatedAt: false,
        createdAt: false,
        
        nestID: {
            type: "string",
            columnType: "varchar",
            required: true,
            unique: true
        },
        createdBy: {
            model: "user",
            required: true
        },
        editedBy: {
            model: "user"
        },
        nestDescription: {
            type: "string",
            columnType: "varchar",
            
        },
        distanceToHoppersKm: {
            type: "ref",
            columnType: "float"
        },
        latitude: {
            type: "ref",
            columnType: "float"
        },
        longitude: {
            type: "ref",
            columnType: "float"
        },
    }
};