/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {
    autoPK: false,
    autoUpdatedAt: false,
    autoCreatedAt: false,

    attributes: {
        userID: {
            type: 'number',
            autoIncrement: true,
            required: true,
            primaryKey: true
        },
        username: {
            type: "string",
            columnType: "varchar",
            maxLength: 20,
            required: true
        },
        fullname: {
            type: "string",
            columnType: "varchar",
            maxLength: 40,
            required: true
        },
        passwordHash: {
            type: "string",
            columnType: "varchar",
            maxLength: 20,
            required: true
        },
        hasRead: {
            type: "boolean"
        },
        hasCreateEdit: {
            type: "boolean"
        },
        hasEditFull: {
            type: "boolean"
        },
        hasExportSimple: {
            type: "boolean"
        },
        hasExportFull: {
            type: "boolean"
        },
        hasAdmin: {
            type: "boolean"
        }
    }
};