/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {

    attributes: {
        //UserID provided by sails ID

        username: {
            type: "string",
            columnType: "varchar",
            maxLength: 20,
            required: true,
            unique: true
        },
        fullName: {
            type: "string",
            columnType: "varchar",
            maxLength: 40,
            required: true
        },
        password: {
            type: "string",
            columnType: "varchar",
            required: true,
            protect: true
        },
        hasRead: {
            type: "boolean"
        },
        hasCreateEdit: { // implies having read
            type: "boolean"
        },
        hasEditFull: { // implies having createEdit and read
            type: "boolean"
        },
        hasExport: { //implies having read aswell
            type: "boolean"
        },
        hasAdmin: { //implies all = user creation
            type: "boolean"
        }
    }
};