/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {

    primaryKey: "visitID",

    attributes: {
        id: false,
        updatedAt: false,
        visitID: {
            type: 'number',
            autoIncrement: true,
            required: true
        },
        feederID: {
            model: "feeder"
        },
        birdID: {
            model: "bird"
        },
        ncfRFIDInternal: {
            model: "rfidtag"
        }
        //CreatedOn (i.e. visit time) Auto made by sails
    }
};