/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {
    attributes: {
        updatedAt: false,
        // feederID: {
        //     model: "feeder"
        // },
        birdID: {
            model: "bird"
        },
        ncfRFID: {
            model: "rfidtag"
        }
        //CreatedOn (i.e. visit time) Auto made by sails
    }
};