/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {
    
    attributes: {
        //visitID provided by sails ID
        //CreatedOn (i.e. visit time) Auto made by sails
        updatedAt: false,

        feederID: {
            type: "string",
            columnType: "varchar",
            maxLength: 20,
            required: true
        },
        birdID: {
            model: "bird"
        },
        nfcRFID: {
            model: "rfidtag",
            required: true
        }
       
    }
};