/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {
    autoPK: false,
    autoUpdatedAt: false,

    attributes: {
        birdID: {
            type: 'number',
            autoIncrement: true,
            required: true,
            primaryKey: true
        },
        createdBy: {
            model: "user"
        },
        // createdOn: {
        //     type: "string",
        //     columnType: "datetime",
        //     required: true
        // }, AUTO MADE BY SAILS
        birdName: {
            type: "string",
            columnType: "varchar",
            maxLength: 20
        },
        studID: {
            type: "string",
            columnType: "varchar",
            maxLength: 20,
            unique: true
        },
        newStudID: {
            type: "string",
            columnType: "varchar",
            maxLength: 20,
            unique: true
        },
        leftRingID: {
            type: "string",
            columnType: "varchar",
            maxLength: 30
        },
        rightRingID: {
            type: "string",
            columnType: "varchar",
            maxLength: 30
        },
        sex: {
            type: "string",
            columnType: "enum",
            isIn: ["m", "f"]
        },
        layDate: {
            type: "string",
            columnType: "date"
        },
        hatchedWhere: {
            type: "string",
            columnType: "varchar",
            maxLength: 20
        },
        hatchDate: {
            type: "string",
            columnType: "date"
        },
        incubationDays: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
        birdFledged: {
            type: "boolean"
        },
        fledgedWhere: {
            type: "string",
            columnType: "varchar",
            maxLength: 20
        },
        releasedWhere: {
            type: "string",
            columnType: "varchar",
            maxLength: 20
        },
        releasedWhen: {
            type: "string",
            columnType: "datetime"
        },
        groupName: {
            type: "string",
            columnType: "varchar",
            maxLength: 20
        },
        currentNestSite: {
            model: "nestsite"
        },
        motherName: {
            type: "string",
            columnType: "varchar",
            maxLength: 20
        },
        motherID: {
            model: "bird"
        },
        fatherName: {
            type: "string",
            columnType: "varchar",
            maxLength: 20
        },
        fatherID: {
            model: "bird"
        },
        secondFatherName: {
            type: "string",
            columnType: "varchar",
            maxLength: 20
        },
        secondFatherID: {
            model: "bird"
        },
        researcherNotes: {
            type: "string",
            columnType: "varchar",
            maxLength: 200
        },
        dateOut: { //death date
            type: "string",
            columnType: "date"
        }
    }
};