/**
	Generated by sails-inverse-model
	Date:Thu Jan 24 2019 13:21:47 GMT+0000 (Greenwich Mean Time)
*/

module.exports = {
    autoPK: false,
    autoUpdatedAt: false,
    autoCreatedAt: false,

    attributes: {
        feederID: {
            type: 'number',
            autoIncrement: true,
            required: true,
            primaryKey: true
        },
        createdBy: {
            model: "user"
        },
        feederDescription: {
            type: "string",
            columnType: "varchar",
            maxLength: 200
        }
    }
};